version: '3.8'

services:
  prerender:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Comma-separated list of allowed domains (leave empty to allow all)
      - ALLOWED_DOMAINS=${ALLOWED_DOMAINS:-}
      # User agents to prerender for ('all' or regex pattern)
      - PRERENDER_USER_AGENTS=${PRERENDER_USER_AGENTS:-all}
      # User agents to strip JavaScript for ('none' or regex pattern)
      - STRIP_JS_USER_AGENTS=${STRIP_JS_USER_AGENTS:-}
      # Cache TTL in seconds (0 to disable)
      - CACHE_MAXAGE=${CACHE_MAXAGE:-3600}
      # Port to listen on
      - PORT=${PORT:-3000}
      # Host to bind to
      - HOST=${HOST:-0.0.0.0}
      # Enable request logging
      - LOG_REQUESTS=${LOG_REQUESTS:-true}
      # Wait time in ms after last request
      - WAIT_AFTER_LAST_REQUEST=${WAIT_AFTER_LAST_REQUEST:-500}
      # Follow redirects
      - FOLLOW_REDIRECTS=${FOLLOW_REDIRECTS:-true}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s